@startuml

left to right direction

actor "Admin" as Admin 
actor "Guest" as Guest
actor "User" as User

' Combine Admin and User functionalities into a common group
rectangle "System Functionality" {

  ' Admin Functionality
  usecase "Login" as Login
  usecase "Logout" as Logout
  usecase "Manage Users" as ManageUsers
  usecase "Notifications" as Notifications
  usecase "Edit Profile" as EditProfile
  usecase "Register" as Register

  ' Guest Functionality
  usecase "QR Code Scanner" as QRcode
  usecase "View Map" as ViewMap
  usecase "View User Data" as ViewUserData
  usecase "Wait for Permision" as Permision
}

' Simplified relationships for Guest
Guest -- QRcode
QRcode -- Permision
Permision .> ViewUserData : <<include>>
ViewUserData .> ViewMap : <<include>>

' Simplified relationships for Admin and User
Admin -up- Login
Admin -- EditProfile : <<include>>
Admin -- Notifications : <<include>>
Admin -- ManageUsers : <<include>> 
Admin -- ViewUserData
User -down- Register
Register -- Login : <<include>> 
Login .> Logout : <<include>>


@enduml
